name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@v4.2.2
    with:
      rust-toolchain: stable
      mx-scenario-go-version: v3.0.0
      enable-interactor-tests: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
